### ISSUE TITLE
The size of 128 is not quite right

### ISSUE THREAD

**Issue by catelinaChen** [ed-asriyan/lottie-converter#81]
![CleanShot 2023-02-06 at 12 03 57](https://user-images.githubusercontent.com/69782493/216881323-97d51058-0a64-43e3-ad74-08957dc7da6d.png)

**Comment by ed-asriyan** [comment]
the bug is already solved. please use
* `-e HEIGHT=Y` and/or `-e WIDTH=X` if you use docker
* `--height Y` and/or `--width X` if you use executables

read me in [README](https://github.com/ed-asriyan/lottie-converter/tree/master?tab=readme-ov-file#using-compiled-executables)
