### ISSUE TITLE
Optionally do not draw the outline of the object on a transparent background

### ISSUE THREAD

**Issue by Dmitro25** [ed-asriyan/lottie-converter#87]
Hello! Thanks for the useful application. 
Could you add an option to not draw the outline of an object on a transparent background? The presence of the gray contour is clearly visible in the following picture:

![clipboard](https://github.com/ed-asriyan/lottie-converter/assets/1567817/51af4832-c314-4f85-89de-473c1b9f9f37)

on the left is the result obtained by your application; on the right is the frame of the same animation being played in the browser. The background of the animation is transparent.

**Comment by ed-asriyan** [comment]
@Dmitro25 please switch on [v1.0.1](https://github.com/ed-asriyan/lottie-converter/releases/tag/v1.0.1)

**Comment by Dmitro25** [comment]
Thank you, it works. The outlines are gone.

I would also recommend making the default output path (the "-o" option) not "", but ".", otherwise under Windows without this option the results are saved to an unknown location, otherwise they will be saved to the current folder.
