### ISSUE TITLE
Cant detect Image

### ISSUE THREAD

**Issue by kevaldonga** [ed-asriyan/lottie-converter#92]
here is my file 
[file.json](https://github.com/ed-asriyan/lottie-converter/files/15433423/new.json)

**Comment by ed-asriyan** [comment]
Hi, could you please describe your problem:
* What command do you run?
* What do you expect?
* What do actually happen?

**Comment by kevaldonga** [comment]
it's not complicateed issue i have imagedata in my json file which is not detected and only svg one are printed

**Comment by ed-asriyan** [comment]
just for history: this seems to be the same problem as https://github.com/Samsung/rlottie/issues/407

**Comment by ed-asriyan** [comment]
@kevaldonga please verify that the issue is resolved for you in [v1.1.1](https://github.com/ed-asriyan/lottie-converter/releases/tag/v1.1.1)

**Comment by kevaldonga** [comment]
Yup it's working thanks
